# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/roamer2/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/zte/roamer2/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/zte/roamer2/proprietary/lib/libnv.so:obj/lib/libnv.so

PRODUCT_COPY_FILES += \
    vendor/zte/roamer2/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/roamer2/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/roamer2/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/zte/roamer2/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/roamer2/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/roamer2/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/roamer2/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/roamer2/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/zte/roamer2/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/zte/roamer2/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/zte/roamer2/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/roamer2/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/zte/roamer2/proprietary/etc/BCM4330B1_002.001.032.0518.0520.hcd:system/etc/BCM4330B1_002.001.032.0518.0520.hcd \
    vendor/zte/roamer2/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_mt9p012_preview.so:system/lib/libchromatix_mt9p012_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_mt9t013_preview.so:system/lib/libchromatix_mt9t013_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_ov8810_preview.so:system/lib/libchromatix_ov8810_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_s5k3e2fx_preview.so:system/lib/libchromatix_s5k3e2fx_preview.so \
    vendor/zte/roamer2/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/zte/roamer2/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/zte/roamer2/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/roamer2/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/roamer2/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/roamer2/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
    vendor/zte/roamer2/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/zte/roamer2/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/zte/roamer2/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/zte/roamer2/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/zte/roamer2/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/zte/roamer2/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/zte/roamer2/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/zte/roamer2/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/zte/roamer2/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/zte/roamer2/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/zte/roamer2/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/zte/roamer2/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/zte/roamer2/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/zte/roamer2/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/zte/roamer2/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/zte/roamer2/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/zte/roamer2/proprietary/bin/sapd:system/bin/sapd \
    vendor/zte/roamer2/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/roamer2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/roamer2/proprietary/bin/radish:system/bin/radish \
    vendor/zte/roamer2/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/zte/roamer2/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/zte/roamer2/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/zte/roamer2/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/zte/roamer2/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/zte/roamer2/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/zte/roamer2/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/zte/roamer2/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/roamer2/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/roamer2/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/zte/roamer2/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/roamer2/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/roamer2/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/zte/roamer2/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/roamer2/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/roamer2/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/zte/roamer2/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/roamer2/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/roamer2/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/zte/roamer2/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/roamer2/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/roamer2/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/zte/roamer2/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/zte/roamer2/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/zte/roamer2/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/zte/roamer2/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/roamer2/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/roamer2/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/roamer2/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/roamer2/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/roamer2/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/roamer2/proprietary/lib/libSimCardAuth.so:system/lib/libSimCardAuth.so \
    vendor/zte/roamer2/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/roamer2/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/roamer2/proprietary/bin/akmd8962_new:system/bin/akmd8962_new \
    vendor/zte/roamer2/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/roamer2/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/zte/roamer2/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
    vendor/zte/roamer2/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/zte/roamer2/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-3.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-3.bin \
    vendor/zte/roamer2/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin \
    vendor/zte/roamer2/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin \
    vendor/zte/roamer2/proprietary/wifi/ath6kl_sdio.ko:system/wifi/ath6kl_sdio.ko \
    vendor/zte/roamer2/proprietary/wifi/cfg80211.ko:system/wifi/cfg80211.ko
